#!/usr/bin/env python3
"""Cross-ecosystem GPL/AGPL/LGPL license gate for Statly.

Reads:
  - Python:  `pip-licenses --format=json` output (stdin path via --pip-licenses)
  - JS:      `license-checker-rseidelsohn --production --json` output
  - Rust:    `cargo metadata --format-version 1` output

Fails (non-zero exit) if any *runtime* dependency's license string contains
GPL, AGPL, or LGPL (case-insensitive) -- the owner has banned the entire GPL
family, including LGPL. Entries listed in scripts/license-allowlist.txt
(one `ecosystem:package` per line, '#' comments allowed) are excluded from
the fail set but still appear in the generated THIRD_PARTY_LICENSES.md
table.

With --write PATH, also emits a Markdown table of all runtime deps across
the three ecosystems to PATH.

Usage:
  scripts/check-licenses.py \
      --pip-licenses /tmp/pip-licenses.json \
      --js-licenses /tmp/js-licenses.json \
      --cargo-metadata /tmp/cargo-metadata.json \
      [--write THIRD_PARTY_LICENSES.md]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ALLOWLIST_PATH = REPO_ROOT / "scripts" / "license-allowlist.txt"

BANNED_RE = re.compile(r"(agpl|gpl|lgpl)", re.IGNORECASE)


def load_allowlist() -> set[str]:
    if not ALLOWLIST_PATH.exists():
        return set()
    entries = set()
    for line in ALLOWLIST_PATH.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        entries.add(line)
    return entries


def is_banned(license_str: str) -> bool:
    if not license_str:
        return False
    return bool(BANNED_RE.search(license_str))


def collect_python(path: Path) -> list[dict]:
    data = json.loads(path.read_text())
    rows = []
    for entry in data:
        rows.append(
            {
                "ecosystem": "python",
                "package": entry.get("Name", ""),
                "version": entry.get("Version", ""),
                "license": entry.get("License", "UNKNOWN") or "UNKNOWN",
            }
        )
    return rows


def collect_js(path: Path) -> list[dict]:
    data = json.loads(path.read_text())
    rows = []
    for key, entry in data.items():
        # key looks like "package@version"
        if "@" in key[1:]:
            idx = key.rindex("@")
            name, version = key[:idx], key[idx + 1 :]
        else:
            name, version = key, entry.get("version", "")
        license_val = entry.get("licenses", "UNKNOWN")
        if isinstance(license_val, list):
            license_val = ", ".join(license_val)
        rows.append(
            {
                "ecosystem": "js",
                "package": name,
                "version": version,
                "license": license_val or "UNKNOWN",
            }
        )
    return rows


def collect_rust(path: Path) -> list[dict]:
    data = json.loads(path.read_text())
    workspace_members = set(data.get("workspace_members", []))
    rows = []
    for pkg in data.get("packages", []):
        pkg_id = pkg.get("id", "")
        if pkg_id in workspace_members:
            # Skip our own workspace crate(s).
            continue
        license_val = pkg.get("license") or pkg.get("license_file") or "UNKNOWN"
        rows.append(
            {
                "ecosystem": "rust",
                "package": pkg.get("name", ""),
                "version": pkg.get("version", ""),
                "license": license_val,
            }
        )
    return rows


def write_markdown(rows: list[dict], out_path: Path) -> None:
    lines = [
        "# Third-Party Licenses",
        "",
        "Generated by `scripts/check-licenses.py --write`. Do not edit by hand;",
        "regenerate instead. Covers runtime dependencies across the Python",
        "(engine), JavaScript (app), and Rust (app/src-tauri) ecosystems.",
        "",
        "| Ecosystem | Package | Version | License |",
        "|---|---|---|---|",
    ]
    for row in sorted(rows, key=lambda r: (r["ecosystem"], r["package"].lower())):
        lines.append(
            f"| {row['ecosystem']} | {row['package']} | {row['version']} | {row['license']} |"
        )
    lines.append("")
    out_path.write_text("\n".join(lines))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pip-licenses", type=Path, required=True)
    parser.add_argument("--js-licenses", type=Path, required=True)
    parser.add_argument("--cargo-metadata", type=Path, required=True)
    parser.add_argument("--write", type=Path, default=None)
    args = parser.parse_args()

    rows: list[dict] = []
    rows += collect_python(args.pip_licenses)
    rows += collect_js(args.js_licenses)
    rows += collect_rust(args.cargo_metadata)

    allowlist = load_allowlist()

    hits = []
    for row in rows:
        key = f"{row['ecosystem']}:{row['package']}"
        if key in allowlist:
            continue
        if is_banned(row["license"]):
            hits.append(row)

    if args.write:
        write_markdown(rows, args.write)
        print(f"Wrote {args.write} ({len(rows)} entries)")

    if hits:
        print("GPL-family license violations found:", file=sys.stderr)
        for row in hits:
            print(
                f"  [{row['ecosystem']}] {row['package']} {row['version']}: "
                f"{row['license']}",
                file=sys.stderr,
            )
        print(
            f"\n{len(hits)} violation(s). Add a justified entry to "
            f"{ALLOWLIST_PATH.relative_to(REPO_ROOT)} only for verified false "
            "positives (e.g. dual-licensed 'MIT OR GPL').",
            file=sys.stderr,
        )
        return 1

    print(f"License check clean: {len(rows)} runtime dependencies scanned, 0 GPL-family hits.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
