"""Statly statistics engine (SPEC §8). See stats/README.md for how to add an analysis."""
from statly_engine.stats import anova, posthoc_param  # noqa: E402,F401  (registers the ANOVA family)
from statly_engine.stats import categorical, correlation, reliability  # noqa: E402,F401  (registers correlation, categorical, reliability)
from statly_engine.stats import nonparametric, posthoc_rank  # noqa: E402,F401  (registers the nonparametric family)
from statly_engine.stats import power  # noqa: E402,F401  (registers power.*, dataset-free)
from statly_engine.stats import regression, regression_logistic  # noqa: E402,F401  (registers the regression family)
from statly_engine.stats import ancova, manova, quade  # noqa: E402,F401  (registers ancova, ancova.quade, manova, mancova)
from statly_engine.stats import agreement, education  # noqa: E402,F401  (registers rater agreement + education)
from statly_engine.stats import anova_factorial, anova_mixed, art, posthoc_simple  # noqa: E402,F401  (registers factorial, mixed, ART, simple effects)
from statly_engine.stats import cfa, efa  # noqa: E402,F401  (registers validity.efa, validity.cfa)
