"""Cross-analysis multiple-comparison corrections for Test Log families (SPEC §9).

Pure functions reproducing R's `stats::p.adjust` exactly (validated against
fixtures/expected/corrections/, generated by fixtures/r/corrections.R):

- bonferroni: min(1, n * p)
- holm:       pmin(1, cummax((n - i + 1) * p[o]))[order back],  o = order(p)
- fdr_bh:     pmin(1, cummin(n / i * p[o]))[order back],        o = order(p, decreasing = TRUE)
- none:       p unchanged

Missing p-values (None / NaN) are passed through as None and, like `p.adjust`'s default
`n = length(p[!is.na(p)])`, do not count towards n. Statly never applies these automatically;
the user chooses the family and the method.
"""

from __future__ import annotations

import math
from collections.abc import Sequence

import numpy as np

METHODS = ("none", "bonferroni", "holm", "fdr_bh")


def _is_missing(p) -> bool:
    return p is None or (isinstance(p, float) and math.isnan(p))


def p_adjust(p_values: Sequence[float | None], method: str) -> list[float | None]:
    """Adjusted p-values in the input order (same length; missing stays None)."""
    if method not in METHODS:
        raise ValueError(f"Unknown correction method '{method}'. Use one of: {', '.join(METHODS)}.")
    out: list[float | None] = [None] * len(p_values)
    idx = [i for i, p in enumerate(p_values) if not _is_missing(p)]
    for i in idx:
        p = float(p_values[i])
        if not 0.0 <= p <= 1.0:
            raise ValueError(f"p-values must be between 0 and 1; got {p}.")
    if not idx:
        return out
    p = np.array([float(p_values[i]) for i in idx], dtype=float)
    n = len(p)
    if method == "none" or n == 1:
        adj = p.copy()
    elif method == "bonferroni":
        adj = np.minimum(1.0, n * p)
    elif method == "holm":
        o = np.argsort(p, kind="stable")
        steps = (n - np.arange(n)) * p[o]  # (n - i + 1) * p[o], i = 1..n
        adj = np.empty(n)
        adj[o] = np.minimum(1.0, np.maximum.accumulate(steps))
    else:  # fdr_bh
        o = np.argsort(-p, kind="stable")  # decreasing
        i = np.arange(n, 0, -1)            # n, n-1, ..., 1
        steps = n / i * p[o]
        adj = np.empty(n)
        adj[o] = np.minimum(1.0, np.minimum.accumulate(steps))
    for k, i in enumerate(idx):
        out[i] = float(adj[k])
    return out
